# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('District', 'district'), ('Possession', 'possession'), ('State', 'state'), ('Territory', 'territory')], max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2)),
                ('capital_city', models.CharField(max_length=100)),
                ('data_available', models.BooleanField(default=False)),
                ('data_restrictions', models.CharField(choices=[('No', 'no'), ('Yes', 'yes'), ('Unknown', 'unknown')], default='unknown', max_length=10)),
                ('data_refresh', models.CharField(choices=[('Daily', 'daily'), ('Weekly', 'weekly'), ('Monthly', 'monthly'), ('Semi-Annually', 'semi-annually'), ('Annually', 'annually'), ('Unknown', 'unknown')], default='Unknown', max_length=15)),
                ('data_cost', models.IntegerField(default=0)),
                ('data_source', models.CharField(max_length=100)),
                ('data_url', models.URLField(blank=True, null=True)),
                ('data_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=105)),
                ('is_published', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2015, 12, 11, 23, 23, 23, 13190))),
            ],
        ),
    ]
