# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='category',
            field=models.CharField(choices=[('district', 'District'), ('possession', 'Possession'), ('state', 'State'), ('territory', 'Territory')], default='state', max_length=25),
        ),
        migrations.AlterField(
            model_name='division',
            name='data_refresh',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('semi-annually', 'Semi-Annually'), ('annually', 'Annually'), ('unknown', 'Unknown')], default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='division',
            name='data_restrictions',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 12, 45, 25, 813323)),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=models.SlugField(max_length=105, unique=True),
        ),
    ]
