# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151212_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='data_source',
            field=models.CharField(default='Department of State', max_length=100),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 12, 47, 34, 498958)),
        ),
    ]
