# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151212_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 15, 43, 44, 248295)),
        ),
    ]
