# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20151212_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='data_status',
            field=models.CharField(default='unavailable', max_length=25),
        ),
        migrations.AlterField(
            model_name='division',
            name='data_refresh',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('semi-annually', 'Semi-Annually'), ('annually', 'Annually'), ('unknown', 'Unknown')], default='unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 15, 9, 1, 879014)),
        ),
    ]
