# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20151215_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='data_status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('published', 'Published'), ('unavailable', 'Unavailable'), ('under review', 'Under Review')], default='unavailable', max_length=25),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 18, 29, 59, 781583)),
        ),
    ]
