# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20151226_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='division',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 7, 59, 11, 426766)),
        ),
    ]
