# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:16
from __future__ import unicode_literals

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20151226_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_file',
            field=models.FileField(upload_to=core.models.data_set_location),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 27, 8, 16, 26, 695459)),
        ),
    ]
