# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20151227_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2015, 12, 27, 8, 32, 12, 782819)),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 27, 8, 32, 12, 780763)),
        ),
    ]
