# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20151227_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 27, 13, 34, 31, 662478, tzinfo=utc)),
        ),
    ]
