# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20151227_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
